apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "team-a-cq"
spec:
  namespaceSelector: {} # match all.
  cohort: "team-ab"
  resourceGroups:
    - coveredResources: ["cpu", "memory"]
      flavors:
        - name: "standard"
          resources:
            - name: "cpu"
              nominalQuota: 1
            - name: "memory"
              nominalQuota: 36Gi
        - name: "spot"
          resources:
            - name: "cpu"
              nominalQuota: 1
            - name: "memory"
              nominalQuota: 72Gi
---
apiVersion: kueue.x-k8s.io/v1beta1
kind: ClusterQueue
metadata:
  name: "team-b-cq"
spec:
  namespaceSelector: {} # match all.
  cohort: "team-ab"
  resourceGroups:
    - coveredResources: ["cpu", "memory"]
      flavors:
        - name: "standard"
          resources:
            - name: "cpu"
              nominalQuota: 1
            - name: "memory"
              nominalQuota: 36Gi
