apiVersion: batch/v1
kind: Job
metadata:
  namespace: team-b # Job under team-b namespace
  generateName: sample-job-team-b-
  annotations:
    kueue.x-k8s.io/queue-name: lq-team-b # Point to the LocalQueue
spec:
  # ttlSecondsAfterFinished: 60 # Job will be deleted after 60 seconds
  parallelism: 1 # This Job will have 1 replicas running at the same time
  completions: 1 # This Job requires 1 completions
  suspend: true # Set to true to allow Kueue to control the Job when it starts
  template:
    spec:
      containers:
      - name: dummy-job
        image: gcr.io/k8s-staging-perf-tests/sleep:latest
        args: ["10s"] # Sleep for 10 seconds
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      restartPolicy: Never